version: '3.8'

networks:
  default:
    driver: bridge
    external: false

services:
  goat-mysql:
    build: ./mysql/
    image: sun/goat-mysql:latest
    container_name: goat-mysql
    restart: on-failure
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 10101010
      MYSQL_DATABASE: GoatMilk
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  goat-redis:
    image: redis:alpine
    container_name: goat-redis
    restart: on-failure
  
  goat-img-file:
    build: ./GoatMilkFile/
    image: sun/goat-milk-file:latest
    container_name: goat-img-file
    restart: on-failure
    volumes:
      - ./GoatMilkFile/static:/GoatMilkFile/static
    environment:
      MYSQL_HOST: goat-mysql
    depends_on:
      - goat-mysql
  
  goat-milk-powder:
    build: ./GoatMilkPowder/
    image: sun/goat-milk-powder:latest
    container_name: goat-milk-powder
    restart: on-failure
    environment: 
      MYSQL_HOST: goat-mysql
      REDIS_HOST: goat-redis
    depends_on: 
      - goat-mysql
      - goat-redis
    
  goat-milk-web:
    build: ./GoatMilkWeb/
    image: sun/goat-milk-web:latest
    container_name: goat-milk-web
    restart: on-failure
    depends_on: 
      - goat-img-file
      - goat-milk-powder
  
  goat-nginx:
    image: nginx:stable-alpine
    container_name: goat-nginx
    restart: on-failure
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - goat-img-file
      - goat-milk-powder
      - goat-milk-web
