version: '3.8'

networks:
  default:
    driver: bridge
    external: false

services:
  goat-postgresql:
    build: ./postgresql/
    image: sun/goat-postgresql:latest
    container_name: goat-postgresql
    restart: on-failure
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=10101010
      - POSTGRES_DB=GoatMilk
    # ports:
    #     - "5432:5432"

  goat-redis:
    image: redis:alpine
    container_name: goat-redis
    restart: on-failure

  goat-img-file:
    build: ./GoatMilkFile/
    image: sun/goat-milk-file:latest
    container_name: goat-img-file
    restart: on-failure
    volumes:
      - ./GoatMilkFile/static:/GoatMilkFile/static
    environment:
      PYTHONUNBUFFERED: 1
      POSTGRESQL_HOST: goat-postgresql
    depends_on:
      - goat-postgresql

  goat-milk-powder:
    build: ./GoatMilkPowder/
    image: sun/goat-milk-powder:latest
    container_name: goat-milk-powder
    restart: on-failure
    environment: 
      POSTGRESQL_HOST: goat-postgresql
      REDIS_HOST: goat-redis
    depends_on: 
      - goat-postgresql
      - goat-redis

  goat-milk-web:
    build: ./GoatMilkWeb/
    image: sun/goat-milk-web:latest
    container_name: goat-milk-web
    restart: on-failure
    ports:
      - "8080:80"
    depends_on:
      - goat-img-file
      - goat-milk-powder

  # goat-nginx:
  #   image: nginx:stable-alpine
  #   container_name: goat-nginx
  #   restart: on-failure
  #   volumes:
  #     - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - goat-img-file
  #     - goat-milk-powder
  #     - goat-milk-web
