spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/GoatMilk?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: goat
    password: goat
    driver-class-name: com.mysql.cj.jdbc.Driver
    sql-script-encoding: utf-8
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  redis:
    host: ${REDIS_HOST}
    port: 6379

server:
  port: 8080

# logging:
#   level:
#     '[org.springframework]': error
