spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:5432/GoatMilk
    username: postgres
    password: 10101010
    driver-class-name: org.postgresql.Driver
    sql-script-encoding: utf-8
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
      temp:
        use_jdbc_metadata_defaults: false
  redis:
    host: ${REDIS_HOST}
    port: 6379

server:
  port: 8080

logging:
  level:
    '[org.springframework]': error
