--
-- PostgreSQL database dump
--

-- Dumped from database version 13.3
-- Dumped by pg_dump version 13.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: 公司自检_生羊乳_样品; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."公司自检_生羊乳_样品" (
    id bigint NOT NULL,
    dbp character varying(255),
    "β_内酰胺酶" character varying(255),
    "冰点" character varying(255),
    "奶站" character varying(255),
    "感官" character varying(255),
    "抗生素" character varying(255),
    "日期" character varying(255),
    "煮沸试验" character varying(255),
    "脂肪" character varying(255),
    "蛋白质" character varying(255),
    "酒精试验" character varying(255),
    "酸度" character varying(255),
    "非脂乳固体" character varying(255)
);


ALTER TABLE public."公司自检_生羊乳_样品" OWNER TO postgres;

--
-- Name: 公司自检_生羊乳_样品_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."公司自检_生羊乳_样品" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."公司自检_生羊乳_样品_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: 用户; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."用户" (
    username character varying(255) NOT NULL,
    password character varying(255),
    role character varying(255)
);


ALTER TABLE public."用户" OWNER TO postgres;

--
-- Name: 羊奶粉dna含量; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."羊奶粉dna含量" (
    id bigint NOT NULL,
    abs260 double precision NOT NULL,
    abs260_280 double precision NOT NULL,
    abs280 double precision NOT NULL,
    dna_content double precision NOT NULL
);


ALTER TABLE public."羊奶粉dna含量" OWNER TO postgres;

--
-- Name: 羊奶粉dna含量_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."羊奶粉dna含量" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."羊奶粉dna含量_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: 羊奶粉产品检测_国产进口_样品; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."羊奶粉产品检测_国产进口_样品" (
    id bigint NOT NULL,
    ara character varying(255),
    ala character varying(255),
    arg character varying(255),
    asp character varying(255),
    dha character varying(255),
    glu character varying(255),
    gly character varying(255),
    his character varying(255),
    ile character varying(255),
    leu character varying(255),
    lys character varying(255),
    met character varying(255),
    opo character varying(255),
    phe character varying(255),
    pro character varying(255),
    ser character varying(255),
    thr character varying(255),
    tyr character varying(255),
    val character varying(255),
    info character varying(255),
    "α_亚麻酸" character varying(255),
    "乳糖" character varying(255),
    "亚油酸" character varying(255),
    "亚油酸_α_亚麻酸" character varying(255),
    "反式脂肪酸与总脂肪酸的比值" character varying(255),
    "叶酸" character varying(255),
    "品种" character varying(255),
    "总砷" character varying(255),
    "月桂酸和肉豆蔻酸占总脂肪酸的比例" character varying(255),
    "氨基酸总量" character varying(255),
    "氯" character varying(255),
    "水分" character varying(255),
    "泛酸" character varying(255),
    "灰分" character varying(255),
    "烟酸" character varying(255),
    "生物素" character varying(255),
    "硒" character varying(255),
    "碘" character varying(255),
    "碳水化合物" character varying(255),
    "磷" character varying(255),
    "组织状态" character varying(255),
    "维生素a" character varying(255),
    "维生素b1" character varying(255),
    "维生素b12" character varying(255),
    "维生素b2" character varying(255),
    "维生素b6" character varying(255),
    "维生素c" character varying(255),
    "维生素d" character varying(255),
    "维生素e" character varying(255),
    "维生素k1" character varying(255),
    "胆碱" character varying(255),
    "脂肪" character varying(255),
    "色泽" character varying(255),
    "蔗糖" character varying(255),
    "蛋白质" character varying(255),
    "酸度" character varying(255),
    "钙" character varying(255),
    "钠" character varying(255),
    "钾" character varying(255),
    "铁" character varying(255),
    "铅" character varying(255),
    "铜" character varying(255),
    "铬" character varying(255),
    "锌" character varying(255),
    "锰" character varying(255),
    "镁" character varying(255),
    "镉" character varying(255)
);


ALTER TABLE public."羊奶粉产品检测_国产进口_样品" OWNER TO postgres;

--
-- Name: 羊奶粉产品检测_国产进口_样品_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."羊奶粉产品检测_国产进口_样品" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."羊奶粉产品检测_国产进口_样品_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: 羊奶粉产品检测_省内外_样品; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."羊奶粉产品检测_省内外_样品" (
    id character varying(255) NOT NULL,
    dbp character varying(255),
    info character varying(255),
    "β_内酰胺酶" character varying(255),
    "区域" character varying(255),
    "感官" character varying(255),
    "抗生素" character varying(255),
    "水分" character varying(255),
    "脂肪" character varying(255),
    "蛋白质" character varying(255),
    "酸度" character varying(255)
);


ALTER TABLE public."羊奶粉产品检测_省内外_样品" OWNER TO postgres;

--
-- Name: 公司自检_生羊乳_样品_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."公司自检_生羊乳_样品_id_seq"', 1, false);


--
-- Name: 羊奶粉dna含量_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."羊奶粉dna含量_id_seq"', 1, false);


--
-- Name: 羊奶粉产品检测_国产进口_样品_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."羊奶粉产品检测_国产进口_样品_id_seq"', 1, false);


--
-- Name: 公司自检_生羊乳_样品 公司自检_生羊乳_样品_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."公司自检_生羊乳_样品"
    ADD CONSTRAINT "公司自检_生羊乳_样品_pkey" PRIMARY KEY (id);


--
-- Name: 用户 用户_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."用户"
    ADD CONSTRAINT "用户_pkey" PRIMARY KEY (username);


--
-- Name: 羊奶粉dna含量 羊奶粉dna含量_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."羊奶粉dna含量"
    ADD CONSTRAINT "羊奶粉dna含量_pkey" PRIMARY KEY (id);


--
-- Name: 羊奶粉产品检测_国产进口_样品 羊奶粉产品检测_国产进口_样品_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."羊奶粉产品检测_国产进口_样品"
    ADD CONSTRAINT "羊奶粉产品检测_国产进口_样品_pkey" PRIMARY KEY (id);


--
-- Name: 羊奶粉产品检测_省内外_样品 羊奶粉产品检测_省内外_样品_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."羊奶粉产品检测_省内外_样品"
    ADD CONSTRAINT "羊奶粉产品检测_省内外_样品_pkey" PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

